inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Lint/Void:
  Enabled: false
Style/FormatString:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/VariableNumber:
  EnforcedStyle: 'snake_case'
Style/RegexpLiteral:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
